In [ ]:
#problem 1
# Initialize an empty array with size 2X2.
import numpy as np
n= np.empty((2,2))
print(n)

[[6.61217384e-310 0.00000000e+000]
 [6.25285810e-091 4.08467246e+179]]


In [ ]:
 #Initialize an all one array with size 4X2
import numpy as np
n1=np.zeros([4,2])
print(n1)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
#Return a new array of given shape and type, filled with fill value.{Hint: np.full}
import numpy as np
fill_value=5
filled_array=np.full((2,2),fill_value)
print(filled_array)


[[5 5]
 [5 5]]


In [ ]:
# Return a new array of zeros with same shape and type as a given array.
import numpy as np
arrays=np.array([[1,2],[3,4]])
print(np.zeros_like(arrays))


[[0 0]
 [0 0]]


In [ ]:
# Return a new array of ones with same shape and type as a given array.
import numpy as np
arrays=np.array([[1,2],[3,4]])
print(np.ones_like(arrays))


[[1 1]
 [1 1]]


In [ ]:
# 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
import numpy as np
new_list=[1,2,3,4]
print(np.array(new_list))

[1 2 3 4]


In [ ]:
#problem2
# 1. Create an array with values ranging from 10 to 49.
value=np.arange(10,50)
print(value)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8.
import numpy as np
array=np.arange(0,9)
matrix=np.reshape(array,(3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#3.create 3x3 identity matrix
array=np.eye(3,3)
print(array)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Create a random array of size 30 and find the mean of the array.
#{Hint:check for np.random.random() and array.mean() function}
arrays=np.random.random(30)
print("the randome numbers",arrays)
print("The mean of the random number is ",np.mean(arrays))



[0.13191377 0.71635141 0.23719647 0.16481019 0.46685774 0.57380368
 0.8498159  0.58602188 0.4117075  0.97780306 0.2664107  0.50230144
 0.21935948 0.89995075 0.59877059 0.41569809 0.19273922 0.77914964
 0.07891481 0.59004194 0.4154863  0.04313659 0.42122755 0.08096679
 0.3045144  0.76417101 0.06939091 0.21962542 0.10835373 0.00915094]
0.403188063861981


In [ ]:
# 5. Create a 10X10 array with random values and find the minimum and maximum values.
array=np.random.random([10,10])
print(array)
print("the maximum value ",np.max(array))
print("the minimum value",np.min(array))

[[0.1087963  0.35482298 0.67767096 0.97958676 0.31339873 0.03942206
  0.01311897 0.75537551 0.74088412 0.2302827 ]
 [0.8725382  0.7827739  0.05072188 0.79294938 0.27219924 0.71119863
  0.66983156 0.53527241 0.66629614 0.27632568]
 [0.06196577 0.28235163 0.91124939 0.99819425 0.52324375 0.84876642
  0.97754509 0.60359045 0.88370737 0.5565283 ]
 [0.60095033 0.44384405 0.71040134 0.39763446 0.06673447 0.12850088
  0.95960551 0.41177548 0.80889413 0.00991241]
 [0.81280516 0.53768753 0.64673495 0.31085259 0.22442358 0.1524662
  0.62607711 0.64133185 0.29049982 0.77732212]
 [0.49379894 0.76370329 0.37754203 0.23750683 0.57048749 0.84485672
  0.0134386  0.12221157 0.20526146 0.85065481]
 [0.09750252 0.70041675 0.8510754  0.49459018 0.50079309 0.48574094
  0.54636544 0.04983855 0.95361101 0.48021865]
 [0.05723896 0.82467667 0.2090257  0.57282168 0.28020744 0.38814484
  0.41420764 0.0687801  0.57784059 0.57582744]
 [0.44341977 0.25152576 0.40324999 0.23177382 0.19143601 0.0268263
  0.25101242 0

In [ ]:
# 6.Create a zero array of size 10 and replace 5th element with 1
array=np.zeros(10)
array[4]=1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 7. Reverse an array arr = [1,2,0,0,4,0].
arr=[1,2,0,0,4,0]
print(np.flip(arr))


[0 4 0 0 2 1]


In [ ]:
# Create a 2d array with 1 on border and 0 inside
array=np.zeros((5,5))
array[0, :] = 1 # Top row
array[-1, :] = 1 # Bottom row
array[:, 0] = 1 # Left column
array[:, -1] = 1 # Right column
print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# 9. Create a 8X8 matrix and fill it with a checkerboard pattern.
import numpy as np

# Create an 8x8 matrix
matrix = np.zeros((8, 8), dtype=int)

# Fill the matrix with a checkerboard pattern
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#Problem3
#For the following arrays:
#x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
#v = np.array([9,10]) and w = np.array([11,12]);
#Complete all the task using numpy:
#1. Add the two array.
#2. Subtract the two array.
#3. Multiply the array with any integers of your choice.
#4. Find the square of each element of the array.
#5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
#6. Concatenate x(and)y along row and Concatenate v(and)w along column.
#{Hint:try np.concatenate() or np.vstack() functions.
#7. Concatenate x(and)v; if you get an error, observe and explain why did
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);
print("The addition of the two array",np.add(x,y))
print("The subtraction of two array",np.subtract(v,w))
print("The multiplication ",np.multiply(2,x))
print("The square of x",np.square(x))
print("The square of y",np.square(y))
print("The square of v",np.square(v))
print("The square of w",np.square(w))
print("the dot product of v and w",np.dot(v,w))
print("the dot product of x and v",np.dot(x,v))
print("the dot product of x and y",np.dot(x,y))



The addition of the two array [[ 6  8]
 [10 13]]
The subtraction of two array [-2 -2]
The multiplication  [[ 2  4]
 [ 6 10]]
The square of x [[ 1  4]
 [ 9 25]]
The square of y [[25 36]
 [49 64]]
The square of v [ 81 100]
The square of w [121 144]
the dot product of v and w 219
the dot product of x and v [29 77]
the dot product of x and y [[19 22]
 [50 58]]


In [ ]:
#Problem4:
#For the following arrays:
 #A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
 #Prove following with Numpy:
 #1. Prove A.A−1 = I.
 #2. Prove AB= BA.
 #3. Prove (AB)T = BTAT.
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
#2. Prove AB= BA
AB=np.dot(A,B)
BA=np.dot(B,A)
print("The dot product of AB is",AB)
print("The dot product of BA is",BA)
#3. Prove (AB)T = BTAT.
AB=np.dot(A,B)
ABT=np.transpose(AB)
BT=np.transpose(B)
AT=np.transpose(A)
BT_AT=np.dot(BT,AT)
print("(AB)T=",ABT)
print("BT_AT=",BT_AT)






The dot product of AB is [[23 13]
 [51 29]]
The dot product of BA is [[36 44]
 [13 16]]
(AB)T= [[23 51]
 [13 29]]
BT_AT= [[23 51]
 [13 29]]


In [ ]:
#how fast is numpy
#Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure and Print the time taken for this operation.
import time
import random
list1=[]
list2=[]
addition=[]
for i in range(1000000):
  list1.append(random.randint(0,100))
  list2.append(random.randint(0,100))
startTime=time.time()

for i in range(1000000):
  addition.append(list1[i]+list2[i])
endTime=time.time()

totalTimeTaken=endTime-startTime
print("Total time taken when adding two list",totalTimeTaken)

Total time taken when adding two list 0.23402976989746094


In [ ]:
# Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operations.
import numpy as np
import time
import random

addition=[]
array1=np.random.randint(1,10,size=1000000)
array2=np.random.randint(1,10,size=1000000)
startTime=time.time()
addition=np.add(array1,array2)
endTime=time.time()
totalTimeTaken=endTime-startTime
print("Total time taken when adding two list",totalTimeTaken)

Total time taken when adding two list 0.004617452621459961


In [ ]:
# Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000. Measure and Print the time taken for this operation
import numpy as np
import time
import random

multiplication=[]
array1=np.random.randint(1,10,size=1000000)
array2=np.random.randint(1,10,size=1000000)
startTime=time.time()
multiplication=np.multiply(array1,array2)
endTime=time.time()
totalTimeTaken=endTime-startTime
print("Total time taken when multiplying two list",totalTimeTaken)

Total time taken when multiplying two list 0.004762887954711914
